{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "489b9bef-b2d4-4cc7-bba8-f756236c9e6c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# =============================================================================\n",
    "# Phase 9 — Apache Airflow Orchestration\n",
    "# Vehicle Market Analytics Pipeline DAG\n",
    "# =============================================================================\n",
    "#\n",
    "# Requirements:\n",
    "#   Python 3.11 (not 3.13 — ecosystem compatibility)\n",
    "#\n",
    "# Installation:\n",
    "#   python3.11 -m pip install apache-airflow==3.2.1 papermill \\\n",
    "#     --constraint \"https://raw.githubusercontent.com/apache/airflow/\\\n",
    "# constraints-3.2.1/constraints-3.11.txt\"\n",
    "#\n",
    "#   python3.11 -m pip install apache-airflow-providers-standard\n",
    "#\n",
    "# Initialization:\n",
    "#   export AIRFLOW_HOME=~/airflow\n",
    "#   airflow db init\n",
    "#   airflow users create \\\n",
    "#     --username admin --password admin \\\n",
    "#     --firstname Admin --lastname User \\\n",
    "#     --role Admin --email admin@example.com\n",
    "#\n",
    "# Place this file at: $AIRFLOW_HOME/dags/vehicle_market_pipeline.py\n",
    "# =============================================================================\n",
    "\n",
    "import os\n",
    "import subprocess\n",
    "import logging\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "from airflow import DAG\n",
    "from airflow.operators.python import PythonOperator\n",
    "from airflow.operators.bash import BashOperator\n",
    "from airflow.providers.standard.operators.empty import EmptyOperator\n",
    "from airflow.utils.trigger_rule import TriggerRule\n",
    "\n",
    "log = logging.getLogger(__name__)\n",
    "\n",
    "# =============================================================================\n",
    "# CONFIG\n",
    "# =============================================================================\n",
    "\n",
    "PROJECT_BASE  = os.path.expanduser(\"/Users/huntstar/Projects/Vehical_Project\")\n",
    "NOTEBOOKS_DIR = f\"{PROJECT_BASE}/notebooks\"\n",
    "LOGS_DIR      = f\"{PROJECT_BASE}/airflow_logs\"\n",
    "\n",
    "NOTEBOOKS = {\n",
    "    # \"profiling\" : f\"{NOTEBOOKS_DIR}/01_Data_Profiling.ipynb\",\n",
    "    \"etl\"       : f\"{NOTEBOOKS_DIR}/01_Bronze_to_Silver_ETL.ipynb\",\n",
    "    \"features\"  : f\"{NOTEBOOKS_DIR}/03_Feature_Engineering.ipynb\",\n",
    "    \"gold\"      : f\"{NOTEBOOKS_DIR}/04_Gold_ETL.ipynb\",\n",
    "    \"hive\"      : f\"{NOTEBOOKS_DIR}/05_Hive_Data_Warehouse.ipynb\",\n",
    "    \"kafka\"     : f\"{NOTEBOOKS_DIR}/06_Kafka_Producer.ipynb\",\n",
    "    \"streaming\" : f\"{NOTEBOOKS_DIR}/07_Spark_Structured_Streaming.ipynb\",\n",
    "    \"hbase\"     : f\"{NOTEBOOKS_DIR}/08_HBase_Storage.ipynb\",\n",
    "}\n",
    "\n",
    "# Service check commands\n",
    "# HBase uses HappyBase (the same interface used in Phase 8)\n",
    "# rather than the HBase shell — faster and validates the actual write path\n",
    "SERVICE_CHECKS = {\n",
    "    \"HDFS\": (\n",
    "        \"hdfs dfs -ls / > /dev/null 2>&1\"\n",
    "    ),\n",
    "    \"YARN\": (\n",
    "        \"yarn node -list > /dev/null 2>&1\"\n",
    "    ),\n",
    "    \"Hive Metastore\": (\n",
    "        \"hive -e 'SHOW DATABASES;' > /dev/null 2>&1\"\n",
    "    ),\n",
    "    \"ZooKeeper\": (\n",
    "        \"echo ruok | nc localhost 2181 | grep -q imok\"\n",
    "    ),\n",
    "    \"Kafka\": (\n",
    "        \"kafka-topics.sh --bootstrap-server localhost:9092 \"\n",
    "        \"--list > /dev/null 2>&1\"\n",
    "    ),\n",
    "}\n",
    "\n",
    "# Gold HDFS paths validated before Hive table creation\n",
    "GOLD_PATHS = [\n",
    "    \"/user/vehicle_market/gold/kpi_summary\",\n",
    "    \"/user/vehicle_market/gold/manufacturer_summary\",\n",
    "    \"/user/vehicle_market/gold/state_summary\",\n",
    "    \"/user/vehicle_market/gold/monthly_summary\",\n",
    "    \"/user/vehicle_market/gold/fuel_summary\",\n",
    "    \"/user/vehicle_market/gold/segment_summary\",\n",
    "    \"/user/vehicle_market/gold/condition_summary\",\n",
    "    \"/user/vehicle_market/gold/title_summary\",\n",
    "    \"/user/vehicle_market/gold/transmission_summary\",\n",
    "    \"/user/vehicle_market/gold/state_manufacturer\",\n",
    "    \"/user/vehicle_market/gold/manufacturer_condition\",\n",
    "]\n",
    "\n",
    "PAPERMILL_CMD = \"papermill {input} {output} --log-output\"\n",
    "\n",
    "# =============================================================================\n",
    "# DEFAULT ARGS\n",
    "# =============================================================================\n",
    "# start_date=datetime(2026, 7, 1)\n",
    "default_args = {\n",
    "    \"owner\"            : \"vehicle_market\",\n",
    "    \"depends_on_past\"  : False,\n",
    "    \"start_date\"       : datetime(2026, 7, 22),\n",
    "    \"email_on_failure\" : False,\n",
    "    \"email_on_retry\"   : False,\n",
    "    \"retries\"          : 1,\n",
    "    \"retry_delay\"      : timedelta(minutes=5),\n",
    "    \"execution_timeout\": timedelta(hours=2),\n",
    "}\n",
    "\n",
    "# =============================================================================\n",
    "# HELPER FUNCTIONS\n",
    "# =============================================================================\n",
    "\n",
    "def check_services(**context):\n",
    "    \"\"\"\n",
    "    Verify all required services are running before the pipeline starts.\n",
    "    HBase is validated via HappyBase connection rather than the HBase shell\n",
    "    — this is faster and validates the actual interface used in Phase 8.\n",
    "    Raises immediately if any service is unavailable.\n",
    "    \"\"\"\n",
    "    log.info(\"=\"*55)\n",
    "    log.info(\"  Service Health Check\")\n",
    "    log.info(\"=\"*55)\n",
    "\n",
    "    failed_services = []\n",
    "\n",
    "    # Check all standard services via shell commands\n",
    "    for service_name, check_cmd in SERVICE_CHECKS.items():\n",
    "        try:\n",
    "            result = subprocess.run(\n",
    "                check_cmd,\n",
    "                shell=True,\n",
    "                capture_output=True,\n",
    "                text=True,\n",
    "                timeout=30\n",
    "            )\n",
    "            if result.returncode == 0:\n",
    "                log.info(f\"  ✓ {service_name:<20} — running\")\n",
    "            else:\n",
    "                log.error(f\"  ✗ {service_name:<20} — NOT RUNNING\")\n",
    "                log.error(f\"    stderr: {result.stderr.strip()}\")\n",
    "                failed_services.append(service_name)\n",
    "        except subprocess.TimeoutExpired:\n",
    "            log.error(f\"  ✗ {service_name:<20} — TIMEOUT\")\n",
    "            failed_services.append(service_name)\n",
    "        except Exception as e:\n",
    "            log.error(f\"  ✗ {service_name:<20} — ERROR: {e}\")\n",
    "            failed_services.append(service_name)\n",
    "\n",
    "    # Check HBase via HappyBase — validates the actual Thrift write path\n",
    "    try:\n",
    "        import happybase\n",
    "        conn = happybase.Connection(\"localhost\", timeout=10000)\n",
    "        conn.open()\n",
    "        conn.tables()   # lightweight call to confirm connection is live\n",
    "        conn.close()\n",
    "        log.info(f\"  ✓ {'HBase (HappyBase)':<20} — running\")\n",
    "    except ImportError:\n",
    "        log.error(\n",
    "            \"  ✗ HBase (HappyBase)  — happybase not installed.\\n\"\n",
    "            \"    Install with: pip install happybase\"\n",
    "        )\n",
    "        failed_services.append(\"HBase\")\n",
    "    except Exception as e:\n",
    "        log.error(\n",
    "            f\"  ✗ {'HBase (HappyBase)':<20} — NOT RUNNING\\n\"\n",
    "            f\"    Details: {e}\\n\"\n",
    "            f\"    Start HBase Thrift: $HBASE_HOME/bin/hbase thrift start &\"\n",
    "        )\n",
    "        failed_services.append(\"HBase\")\n",
    "\n",
    "    if failed_services:\n",
    "        raise RuntimeError(\n",
    "            f\"The following services are not running: {failed_services}.\\n\"\n",
    "            f\"Start all required services before triggering the pipeline.\\n\"\n",
    "            f\"  HDFS/YARN  : $HADOOP_HOME/sbin/start-all.sh\\n\"\n",
    "            f\"  ZooKeeper  : $KAFKA_HOME/bin/zookeeper-server-start.sh \"\n",
    "            f\"$KAFKA_HOME/config/zookeeper.properties &\\n\"\n",
    "            f\"  Kafka      : $KAFKA_HOME/bin/kafka-server-start.sh \"\n",
    "            f\"$KAFKA_HOME/config/server.properties &\\n\"\n",
    "            f\"  HBase      : $HBASE_HOME/bin/start-hbase.sh\\n\"\n",
    "            f\"  HBase Thrift: $HBASE_HOME/bin/hbase thrift start &\\n\"\n",
    "            f\"  Hive       : hive --service metastore &\"\n",
    "        )\n",
    "\n",
    "    log.info(\"=\"*55)\n",
    "    log.info(\"  All services running. Pipeline cleared to start.\")\n",
    "    log.info(\"=\"*55)\n",
    "\n",
    "\n",
    "def run_notebook(phase_name, notebook_key, **context):\n",
    "    \"\"\"\n",
    "    Execute a Jupyter notebook using papermill.\n",
    "    Saves executed output notebook to LOGS_DIR with timestamp.\n",
    "    Pushes duration and output path to XCom for the report task.\n",
    "    \"\"\"\n",
    "    input_nb  = NOTEBOOKS[notebook_key]\n",
    "    timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "    output_nb = f\"{LOGS_DIR}/{phase_name}_{timestamp}_output.ipynb\"\n",
    "\n",
    "    os.makedirs(LOGS_DIR, exist_ok=True)\n",
    "\n",
    "    if not os.path.exists(input_nb):\n",
    "        raise FileNotFoundError(\n",
    "            f\"Notebook not found: {input_nb}\\n\"\n",
    "            f\"Ensure all notebooks exist at: {NOTEBOOKS_DIR}\"\n",
    "        )\n",
    "\n",
    "    cmd = PAPERMILL_CMD.format(input=input_nb, output=output_nb)\n",
    "\n",
    "    log.info(f\"Executing: {input_nb}\")\n",
    "    log.info(f\"Output   : {output_nb}\")\n",
    "\n",
    "    phase_start = datetime.now()\n",
    "\n",
    "    result = subprocess.run(\n",
    "        cmd, shell=True, capture_output=True, text=True\n",
    "    )\n",
    "\n",
    "    phase_end    = datetime.now()\n",
    "    duration     = (phase_end - phase_start).seconds\n",
    "    duration_fmt = f\"{duration // 60}m {duration % 60}s\"\n",
    "\n",
    "    if result.returncode != 0:\n",
    "        log.error(f\"  ✗ {phase_name} FAILED after {duration_fmt}\")\n",
    "        log.error(f\"  stdout: {result.stdout[-2000:]}\")\n",
    "        log.error(f\"  stderr: {result.stderr[-2000:]}\")\n",
    "        raise RuntimeError(\n",
    "            f\"Phase '{phase_name}' failed. \"\n",
    "            f\"Check output notebook: {output_nb}\"\n",
    "        )\n",
    "\n",
    "    log.info(f\"  ✓ {phase_name} completed in {duration_fmt}\")\n",
    "\n",
    "    context[\"ti\"].xcom_push(\n",
    "        key=f\"{phase_name}_duration\", value=duration_fmt\n",
    "    )\n",
    "    context[\"ti\"].xcom_push(\n",
    "        key=f\"{phase_name}_output_nb\", value=output_nb\n",
    "    )\n",
    "\n",
    "    return output_nb\n",
    "\n",
    "\n",
    "def validate_hdfs_silver(**context):\n",
    "    \"\"\"\n",
    "    Verify Silver layer HDFS outputs exist after ETL.\n",
    "    Uses hdfs CLI — avoids PySpark import complexity in Airflow worker.\n",
    "    Raises if any expected path is missing.\n",
    "    \"\"\"\n",
    "    SILVER_PATHS = [\n",
    "        \"/user/vehicle_market/silver/vehicles_clean\",\n",
    "        \"/user/vehicle_market/silver/vehicles_featured\",\n",
    "    ]\n",
    "\n",
    "    log.info(\"Validating Silver HDFS outputs...\")\n",
    "    missing = []\n",
    "\n",
    "    for path in SILVER_PATHS:\n",
    "        result = subprocess.run(\n",
    "            f\"hdfs dfs -test -e {path}\",\n",
    "            shell=True, capture_output=True\n",
    "        )\n",
    "        if result.returncode == 0:\n",
    "            log.info(f\"  ✓ {path}\")\n",
    "        else:\n",
    "            log.error(f\"  ✗ MISSING: {path}\")\n",
    "            missing.append(path)\n",
    "\n",
    "    if missing:\n",
    "        raise RuntimeError(\n",
    "            f\"Silver layer outputs missing: {missing}. \"\n",
    "            f\"Review Phase 2 and Phase 3 logs.\"\n",
    "        )\n",
    "\n",
    "    log.info(\"  Silver layer validation passed.\")\n",
    "\n",
    "\n",
    "def validate_gold_outputs(**context):\n",
    "    \"\"\"\n",
    "    Verify all Gold HDFS paths exist and contain data before\n",
    "    Hive external tables are created.\n",
    "    Validates:\n",
    "      - folder exists in HDFS\n",
    "      - folder is non-empty (at least one Parquet file present)\n",
    "    \"\"\"\n",
    "    log.info(\"Validating Gold HDFS outputs...\")\n",
    "    missing  = []\n",
    "    empty    = []\n",
    "\n",
    "    for path in GOLD_PATHS:\n",
    "        # Check folder exists\n",
    "        exists_result = subprocess.run(\n",
    "            f\"hdfs dfs -test -e {path}\",\n",
    "            shell=True, capture_output=True\n",
    "        )\n",
    "        if exists_result.returncode != 0:\n",
    "            log.error(f\"  ✗ MISSING     : {path}\")\n",
    "            missing.append(path)\n",
    "            continue\n",
    "\n",
    "        # Check folder is non-empty\n",
    "        count_result = subprocess.run(\n",
    "            f\"hdfs dfs -count {path}\",\n",
    "            shell=True, capture_output=True, text=True\n",
    "        )\n",
    "        if count_result.returncode == 0:\n",
    "            parts      = count_result.stdout.strip().split()\n",
    "            file_count = int(parts[1]) if len(parts) >= 2 else 0\n",
    "            if file_count == 0:\n",
    "                log.error(f\"  ✗ EMPTY       : {path}\")\n",
    "                empty.append(path)\n",
    "            else:\n",
    "                log.info(f\"  ✓ {path} ({file_count} files)\")\n",
    "        else:\n",
    "            log.warning(f\"  ⚠ Count check failed for {path} — skipping\")\n",
    "\n",
    "    issues = missing + empty\n",
    "    if issues:\n",
    "        raise RuntimeError(\n",
    "            f\"Gold validation failed.\\n\"\n",
    "            f\"  Missing : {missing}\\n\"\n",
    "            f\"  Empty   : {empty}\\n\"\n",
    "            f\"Review Phase 4 (Gold ETL) before proceeding to Hive.\"\n",
    "        )\n",
    "\n",
    "    log.info(f\"  All {len(GOLD_PATHS)} Gold tables validated.\")\n",
    "\n",
    "\n",
    "def generate_pipeline_report(**context):\n",
    "    \"\"\"\n",
    "    Collect XCom metadata from all phases and log a final\n",
    "    pipeline execution summary.\n",
    "    Uses logical_date (Airflow 3) instead of execution_date (Airflow 2).\n",
    "    \"\"\"\n",
    "    ti = context[\"ti\"]\n",
    "\n",
    "    phases = [\n",
    "        \"phase1_profiling\",\n",
    "        \"phase2_etl\",\n",
    "        \"phase3_features\",\n",
    "        \"phase4_gold\",\n",
    "        \"phase5_hive\",\n",
    "        \"phase6_kafka\",\n",
    "        \"phase7_streaming\",\n",
    "        \"phase8_hbase\",\n",
    "    ]\n",
    "\n",
    "    log.info(\"\\n\" + \"=\"*60)\n",
    "    log.info(\"    VEHICLE MARKET PIPELINE — EXECUTION REPORT\")\n",
    "    log.info(\"=\"*60)\n",
    "    log.info(f\"  DAG Run       : {context['run_id']}\")\n",
    "    log.info(f\"  Logical Date  : {context['logical_date']}\")   # Airflow 3\n",
    "    log.info(f\"  Triggered By  : {context['dag_run'].run_type}\")\n",
    "    log.info(\"\")\n",
    "    log.info(f\"  {'Phase':<30} {'Duration':>12}  {'Output Notebook'}\")\n",
    "    log.info(f\"  {'-'*70}\")\n",
    "\n",
    "    for phase in phases:\n",
    "        duration  = ti.xcom_pull(\n",
    "            task_ids=phase, key=f\"{phase}_duration\"\n",
    "        ) or \"N/A\"\n",
    "        output_nb = ti.xcom_pull(\n",
    "            task_ids=phase, key=f\"{phase}_output_nb\"\n",
    "        ) or \"N/A\"\n",
    "        nb_name = os.path.basename(output_nb) if output_nb != \"N/A\" else \"N/A\"\n",
    "        log.info(f\"  {phase:<30} {duration:>12}  {nb_name}\")\n",
    "\n",
    "    log.info(\"\")\n",
    "    log.info(\"  ✓ All phases completed successfully.\")\n",
    "    log.info(\"  ✓ Pipeline execution validated.\")\n",
    "    log.info(\"  ✓ Gold CSVs exported to ~/tableau_data/\")\n",
    "    log.info(\"  ✓ Ready for Tableau dashboard development.\")\n",
    "    log.info(\"=\"*60)\n",
    "\n",
    "\n",
    "# =============================================================================\n",
    "# DAG DEFINITION\n",
    "# =============================================================================\n",
    "\n",
    "with DAG(\n",
    "    dag_id=\"vehicle_market_pipeline\",\n",
    "    description=(\n",
    "        \"End-to-end Vehicle Market Analytics Pipeline — \"\n",
    "        \"Bronze → Silver → Gold → Hive → Kafka → Streaming → HBase\"\n",
    "    ),\n",
    "    default_args=default_args,\n",
    "    schedule=None,              # manual trigger only — dataset is static\n",
    "                                # change to \"@daily\" for scheduled runs\n",
    "    catchup=False,\n",
    "    max_active_runs=1,          # prevent concurrent runs writing to same HDFS paths\n",
    "    tags=[\"vehicle_market\", \"big_data\", \"cdac\"],\n",
    ") as dag:\n",
    "\n",
    "    # =========================================================================\n",
    "    # MARKERS\n",
    "    # EmptyOperator replaces DummyOperator in Airflow 3\n",
    "    # =========================================================================\n",
    "\n",
    "    pipeline_start = EmptyOperator(task_id=\"pipeline_start\")\n",
    "    pipeline_end   = EmptyOperator(\n",
    "        task_id=\"pipeline_end\",\n",
    "        trigger_rule=TriggerRule.ALL_SUCCESS\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # SERVICE HEALTH CHECK\n",
    "    # =========================================================================\n",
    "\n",
    "    service_check = PythonOperator(\n",
    "        task_id=\"service_validation\",\n",
    "        python_callable=check_services,\n",
    "        execution_timeout=timedelta(minutes=5),\n",
    "        retries=0,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 1 — Data Profiling\n",
    "    # =========================================================================\n",
    "\n",
    "    phase1_profiling = PythonOperator(\n",
    "        task_id=\"phase1_profiling\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase1_profiling\", \"notebook_key\": \"profiling\"},\n",
    "        execution_timeout=timedelta(hours=1),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 2 — Bronze → Silver ETL\n",
    "    # =========================================================================\n",
    "\n",
    "    phase2_etl = PythonOperator(\n",
    "        task_id=\"phase2_etl\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase2_etl\", \"notebook_key\": \"etl\"},\n",
    "        execution_timeout=timedelta(hours=2),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # SILVER VALIDATION GATE\n",
    "    # =========================================================================\n",
    "\n",
    "    silver_validation = PythonOperator(\n",
    "        task_id=\"silver_validation\",\n",
    "        python_callable=validate_hdfs_silver,\n",
    "        execution_timeout=timedelta(minutes=10),\n",
    "        retries=0,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 3 — Feature Engineering\n",
    "    # =========================================================================\n",
    "\n",
    "    phase3_features = PythonOperator(\n",
    "        task_id=\"phase3_features\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase3_features\", \"notebook_key\": \"features\"},\n",
    "        execution_timeout=timedelta(hours=1),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 4 — Gold ETL\n",
    "    # =========================================================================\n",
    "\n",
    "    phase4_gold = PythonOperator(\n",
    "        task_id=\"phase4_gold\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase4_gold\", \"notebook_key\": \"gold\"},\n",
    "        execution_timeout=timedelta(hours=1),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # GOLD VALIDATION GATE\n",
    "    # Verifies all 11 Gold folders exist and are non-empty\n",
    "    # before Hive external tables are created\n",
    "    # =========================================================================\n",
    "\n",
    "    gold_validation = PythonOperator(\n",
    "        task_id=\"gold_validation\",\n",
    "        python_callable=validate_gold_outputs,\n",
    "        execution_timeout=timedelta(minutes=10),\n",
    "        retries=0,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 5 — Hive Data Warehouse\n",
    "    # Runs after gold_validation passes\n",
    "    # =========================================================================\n",
    "\n",
    "    phase5_hive = PythonOperator(\n",
    "        task_id=\"phase5_hive\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase5_hive\", \"notebook_key\": \"hive\"},\n",
    "        execution_timeout=timedelta(hours=1),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # EXPORT GOLD CSVs — runs in parallel with phase5_hive\n",
    "    # Both depend only on gold_validation passing\n",
    "    # =========================================================================\n",
    "\n",
    "    export_gold_csv = BashOperator(\n",
    "        task_id=\"export_gold_csv\",\n",
    "        bash_command=\"\"\"\n",
    "            mkdir -p ~/tableau_data\n",
    "\n",
    "            for TABLE in kpi_summary manufacturer_summary state_summary \\\n",
    "                monthly_summary fuel_summary segment_summary \\\n",
    "                condition_summary title_summary transmission_summary \\\n",
    "                state_manufacturer manufacturer_condition; do\n",
    "\n",
    "                echo \"Exporting $TABLE...\"\n",
    "                hdfs dfs -getmerge \\\n",
    "                    /user/vehicle_market/gold/$TABLE \\\n",
    "                    ~/tableau_data/$TABLE.csv\n",
    "\n",
    "                if [ $? -eq 0 ]; then\n",
    "                    ROWS=$(wc -l < ~/tableau_data/$TABLE.csv)\n",
    "                    echo \"  ✓ $TABLE — $ROWS rows\"\n",
    "                else\n",
    "                    echo \"  ✗ $TABLE FAILED\"\n",
    "                    exit 1\n",
    "                fi\n",
    "            done\n",
    "\n",
    "            echo \"All Gold tables exported to ~/tableau_data/\"\n",
    "        \"\"\",\n",
    "        execution_timeout=timedelta(minutes=15),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 6 — Kafka Producer\n",
    "    # =========================================================================\n",
    "\n",
    "    phase6_kafka = PythonOperator(\n",
    "        task_id=\"phase6_kafka\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase6_kafka\", \"notebook_key\": \"kafka\"},\n",
    "        execution_timeout=timedelta(minutes=30),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 7 — Spark Structured Streaming\n",
    "    # retries=0 — streaming failures can corrupt checkpoint state\n",
    "    # =========================================================================\n",
    "\n",
    "    phase7_streaming = PythonOperator(\n",
    "        task_id=\"phase7_streaming\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase7_streaming\", \"notebook_key\": \"streaming\"},\n",
    "        execution_timeout=timedelta(minutes=15),\n",
    "        retries=0,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PHASE 8 — HBase Storage\n",
    "    # =========================================================================\n",
    "\n",
    "    phase8_hbase = PythonOperator(\n",
    "        task_id=\"phase8_hbase\",\n",
    "        python_callable=run_notebook,\n",
    "        op_kwargs={\"phase_name\": \"phase8_hbase\", \"notebook_key\": \"hbase\"},\n",
    "        execution_timeout=timedelta(hours=1),\n",
    "        retries=1,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # PIPELINE REPORT\n",
    "    # =========================================================================\n",
    "\n",
    "    pipeline_report = PythonOperator(\n",
    "        task_id=\"pipeline_report\",\n",
    "        python_callable=generate_pipeline_report,\n",
    "        trigger_rule=TriggerRule.ALL_SUCCESS,\n",
    "    )\n",
    "\n",
    "    # =========================================================================\n",
    "    # TASK DEPENDENCIES\n",
    "    #\n",
    "    # pipeline_start\n",
    "    #        │\n",
    "    #        ▼\n",
    "    # service_validation\n",
    "    #        │\n",
    "    #        ▼\n",
    "    # phase1_profiling\n",
    "    #        │\n",
    "    #        ▼\n",
    "    # phase2_etl\n",
    "    #        │\n",
    "    #        ▼\n",
    "    # silver_validation          ← gate: Silver must exist\n",
    "    #        │\n",
    "    #        ▼\n",
    "    # phase3_features\n",
    "    #        │\n",
    "    #        ▼\n",
    "    # phase4_gold\n",
    "    #        │\n",
    "    #        ▼\n",
    "    # gold_validation            ← gate: all 11 Gold tables must exist + non-empty\n",
    "    #        │\n",
    "    #   ┌────┴────┐\n",
    "    #   ▼         ▼\n",
    "    # phase5_hive  export_gold_csv    ← parallel: both only need Gold ready\n",
    "    #   │\n",
    "    #   ▼\n",
    "    # phase6_kafka\n",
    "    #   │\n",
    "    #   ▼\n",
    "    # phase7_streaming\n",
    "    #   │\n",
    "    #   ▼\n",
    "    # phase8_hbase\n",
    "    #   │\n",
    "    #   ▼\n",
    "    # pipeline_report\n",
    "    #   │\n",
    "    #   ▼\n",
    "    # pipeline_end\n",
    "    # =========================================================================\n",
    "\n",
    "    pipeline_start   >> service_check\n",
    "    service_check    >> phase1_profiling\n",
    "    phase1_profiling >> phase2_etl\n",
    "    phase2_etl       >> silver_validation\n",
    "    silver_validation >> phase3_features\n",
    "    phase3_features  >> phase4_gold\n",
    "    phase4_gold      >> gold_validation\n",
    "    gold_validation  >> [phase5_hive, export_gold_csv]\n",
    "    phase5_hive      >> phase6_kafka\n",
    "    phase6_kafka     >> phase7_streaming\n",
    "    phase7_streaming >> phase8_hbase\n",
    "    phase8_hbase     >> pipeline_report\n",
    "    pipeline_report  >> pipeline_end"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.11",
   "language": "python",
   "name": "python311"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
